ae = ""
clip_l = ""
pretrained_model_name_or_path = ""
t5xxl = ""
output_dir = "/root/sd-scripts/modal_output"
reg_data_dir = ""
sample_prompts = "/root/sd-scripts/datasets/prompt.txt"
train_data_dir = "/root/sd-scripts/datasets"
apply_t5_attn_mask = true
blocks_to_swap = 0
bucket_no_upscale = true
bucket_reso_steps = 32
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
caption_dropout_every_n_epochs = 0
caption_dropout_rate = 0
caption_extension = ".txt"
discrete_flow_shift = 3.1285
double_blocks_to_swap = 0
dynamo_backend = "eager"
enable_bucket = true
epoch = 1
fp8_base = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
guidance_scale = 1.0
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
keep_tokens = 0
learning_rate = 0.0001
log_config = true
log_tracker_name = "Flux"
log_with = ""
loss_type = "l2"
lr_scheduler = "constant_with_warmup"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 200
max_bucket_reso = 2048
max_data_loader_n_workers = 4
max_grad_norm = 0
max_timestep = 1000
max_train_steps = 2000
min_bucket_reso = 256
mixed_precision = "bf16"
model_prediction_type = "raw"
network_alpha = 1
network_args = [ "preset=full", "conv_dim=10000", "conv_alpha=1", "use_tucker=False", "rank_dropout=0", "bypass_mode=False", "dora_wd=False", "module_dropout=0", "factor=8", "use_cp=False", "use_scalar=False", "decompose_both=False", "rank_dropout_scale=False", "algo=lokr", "train_norm=False",]
network_dim = 10000
network_dropout = 0
network_module = "lycoris.kohya"
noise_offset_type = "Original"
optimizer_args = []
optimizer_type = "Automagic_Sinkgd"
output_name = "my_lora"
persistent_data_loader_workers = 1
prior_loss_weight = 0.7
resolution = "1024,1024"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_every_n_steps = 400
save_model_as = "safetensors"
save_precision = "bf16"
save_state_on_train_end = true
scale_weight_norms = 0
sdpa = true
seed = 42
single_blocks_to_swap = 0
skip_cache_check = true
t5xxl_max_token_length = 154
text_encoder_lr = [ 7e-6, 7e-6,]
timestep_sampling = "flux_shift"
train_batch_size = 1
unet_lr = 0.0001
vae_batch_size = 4
wandb_api_key = ""
wandb_run_name = "my_lora"